apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: {{ .Values.leaderElect.enabled }}
      resourceName: 7bfe6d29.aws-auth.samba.tv
kind: ConfigMap
metadata:
  name: aws-auth-operator-manager-config
  labels:
    {{- include "aws-auth-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
