apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "aws-auth-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: aws-auth-operator-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "aws-auth-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: aws-auth-operator-leader-election-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "aws-auth-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: aws-auth-operator-manager-role
rules:
- apiGroups:
  - aws-auth.samba.tv
  resources:
  - maproles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws-auth.samba.tv
  resources:
  - maproles/finalizers
  verbs:
  - update
- apiGroups:
  - aws-auth.samba.tv
  resources:
  - maproles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aws-auth.samba.tv
  resources:
  - mapusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws-auth.samba.tv
  resources:
  - mapusers/finalizers
  verbs:
  - update
- apiGroups:
  - aws-auth.samba.tv
  resources:
  - mapusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "aws-auth-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: aws-auth-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-auth-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: aws-auth-operator-controller-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "aws-auth-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  name: aws-auth-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-auth-operator-manager-role
subjects:
- kind: ServiceAccount
  name: aws-auth-operator-controller-manager
  namespace: {{ .Release.Namespace }}