---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws-auth.samba.tv
  resources:
  - maproles
  - mapusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws-auth.samba.tv
  resources:
  - maproles/finalizers
  - mapusers/finalizers
  verbs:
  - update
- apiGroups:
  - aws-auth.samba.tv
  resources:
  - maproles/status
  - mapusers/status
  verbs:
  - get
  - patch
  - update
